dist: trusty
language: java
env:
  - JAVA_OPTS="-Dgradle.publish.key=${GRADLE_KEY} -Dgradle.publish.secret=${GRADLE_SECRET}"
jdk:
  - openjdk8
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  # deploy jar's when TAG commit is build
  - provider: script
    script: bash gradlew publishPlugins
    on:
      tags: true
